# -*- coding: utf-8 -*-
"""Week3_Exercise_Anish_Rao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaDHXdxnPFcwRa-J_bMff5OOVqfSpOyf

## **Exercise 2: Data Types and Variables**

---
Name - Anish Rao

Student Number - 20066423

Group - C

---

[Colab Notebook Link](https://colab.research.google.com/drive/1jaDHXdxnPFcwRa-J_bMff5OOVqfSpOyf?usp=sharing)

1. Create a variable `age` and assign it the value 25.
"""

age = 25

"""2. Create a variable `name` and assign it a string containing your name."""

name = "Anish Rao"

"""3. Print the type of the variable `age`."""

print(type(age))

"""4. Convert the variable `age` to a string and store it in a new variable `age_str`."""

age_str = str(age)
print(type(age_str))

"""5. Create a variable `height` and assign it the value 175.5 (floating-point number)."""

height = 175.5

"""6. Print the type of the variable `height`."""

print(type(height))

"""7. Create a variable `is_student` and assign it a boolean value representing whether you
are a student or not.
"""

is_student = True

"""8. Print the type of the variable `is_student`."""

print(type(is_student))

"""9. Create a list `colors` containing the names of three colors."""

colors = ["red", "blue", "green"]

"""10. Print the second element of the list `colors`."""

print(colors[1])

"""11. Create a tuple `dimensions` containing the length, width, and height of a box."""

dimensions = (10, 20, 15)

"""12. Print the third element of the tuple `dimensions`."""

print(dimensions[2])

"""13. Create a dictionary `person` with keys "name", "age", and "city", and assign appropriate
values.
"""

person = {"name": "Anish Rao", "age": 25, "city": "Dublin"}

"""14. Print the value associated with the key "age" in the dictionary `person`."""

print(person["age"])

"""15. Create a set `unique_numbers` containing three unique integers."""

unique_numbers = {1, 2, 3}

"""16. Add a new integer to the set `unique_numbers`."""

unique_numbers.add(4)
print(unique_numbers)

"""17. Create a variable `x` and assign it the value 10."""

x = 10

"""18. Increment the value of `x` by 5."""

x += 5
print(x)

"""19. Create a variable `y` and assign it the value of `x` squared."""

y = x ** 2
print(y)

"""20. Swap the values of variables `x` and `y`."""

print("x =", x)
print("y =", y)
x, y = y, x
print("After swapping:")
print("x =", x)
print("y =", y)