# -*- coding: utf-8 -*-
"""20066423_Quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQG87hLftrJMM2XH4A6wsfOjMxmKsLG1

# **Quiz Group - C**

---
Name - Anish Rao

Student Number - 20066423

Group - C

---

[Colab Notebook Link](https://colab.research.google.com/drive/1HQG87hLftrJMM2XH4A6wsfOjMxmKsLG1?usp=sharing)
"""

def check_balance(balance):
    print(f"Your current balance is: €{balance:.2f}")

def deposit_money(balance):
    try:
        amount = float(input("Enter the amount to deposit (€): "))
        if amount <= 0:
            print("Invalid amount! Deposit must be positive. Returning to main menu.")
            return balance
        balance += amount
        print(f"€{amount:.2f} deposited successfully! Your updated balance is €{balance:.2f}.")
        return balance
    except ValueError:
        print("Invalid input. Please enter a numeric amount. Returning to main menu.")
        return balance

def withdraw_money(balance):
    try:
        amount = float(input("Enter the amount to withdraw (€): "))
        if amount <= 0:
            print("Invalid amount! Withdrawal must be positive. Returning to main menu.")
            return balance
        if amount > balance:
            print(f"Insufficient funds! Your available balance is €{balance:.2f}. Returning to main menu.")
            return balance
        balance -= amount
        print(f"€{amount:.2f} withdrawn successfully! Your updated balance is €{balance:.2f}.")
        return balance
    except ValueError:
        print("Invalid input. Please enter a numeric amount. Returning to main menu.")
        return balance

def atm_system():
    balance = 1000.0
    while True:
        print("\nATM Menu:")
        print("1. Check Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Exit")

        choice = input("Select an option (1-4): ")

        if choice == "1":
            check_balance(balance)
        elif choice == "2":
            balance = deposit_money(balance)
        elif choice == "3":
            balance = withdraw_money(balance)
        elif choice == "4":
            print("\nExiting ATM. Thank you!")
            break
        else:
            print("\nInvalid option. Please enter a number between 1 and 4.")

atm_system()