# -*- coding: utf-8 -*-
"""Week4_Exercises_Anish_Rao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-pjDE_iHvY1uOfz9obHv2wV1PreWaQh

## **Exercise 3: Control Flow Statements**

---
Name - Anish Rao

Student Number - 20066423

Group - C

---

[Colab Notebook Link](https://colab.research.google.com/drive/1e-pjDE_iHvY1uOfz9obHv2wV1PreWaQh?usp=sharing)

1. Write a program to check if a given number is positive, negative, or zero.
"""

num = float(input("Enter a number: "))
if num > 0:
    print(f"{num} is Positive")
elif num < 0:
    print(f"{num} is Negative")
else:
    print(f"{num} is Zero")

"""2. Write a program to find the maximum of two numbers."""

def maximum(a, b):
  return a if a > b else b

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print("Maximum:", maximum(num1, num2))

"""3. Write a program to check if a given year is a leap year."""

def is_leap_year(year):
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

year = int(input("Enter a year: "))
if is_leap_year(year):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

"""4. Write a program to print the Fibonacci sequence up to a given number of terms."""

def fibonacci(n):
    fib_seq = [0, 1]
    while fib_seq[-1] + fib_seq[-2] <= n:
        fib_seq.append(fib_seq[-1] + fib_seq[-2])
    return fib_seq

input_number = int(input("Enter a number: "))
print(fibonacci(input_number))

"""5. Write a program to find the factorial of a given number."""

def factorial(n):
    return 1 if n == 0 else n * factorial(n-1)

input_number = int(input("Enter a number: "))
print(f"Factorial of {input_number} is {factorial(input_number)}")

"""6. Write a program to calculate the sum of all numbers from 1 to 100."""

print("Sum from 1 to 100:", sum(range(1, 101)))

"""7. Write a program to print the multiplication table of a given number."""

num = int(input("Enter a number: "))
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

"""8. Write a program to find the prime numbers between 1 and 100."""

for num in range(2, 101):
    if all(num % i != 0 for i in range(2, int(num ** 0.5) + 1)):
        print(num, end=" ")

"""9. Write a program to calculate the average of a list of numbers."""

nums = list(map(float, input("Enter numbers separated by spaces: ").split()))
print("Average:", sum(nums) / len(nums))

"""10. Write a program to count the number of vowels in each string."""

def count_vowels(s):
    return sum(1 for c in s.lower() if c in "aeiou")

input_string = input("Enter a string: ")
print("No. of vowels =",count_vowels(input_string))

"""11. Write a function to calculate the area of a circle given its radius."""

import math
r = float(input("Enter radius: "))
print("Area:", math.pi * r ** 2)

"""12. Write a function to check if a given number is even or odd."""

def check_even_odd(n):
    return "Number is Even" if n % 2 == 0 else "Number is Odd"

num = int(input("Enter a number: "))
print(check_even_odd(num))

"""13. Write a function to reverse a given string."""

s = input("Enter a string: ")
print("Reversed:", s[::-1])

"""14. Write a function to check if a given string is a palindrome."""

def is_palindrome(s):
    return "Palindrome" if s == s[::-1] else "Not a Palindrome"

print(is_palindrome("racecar"))
print(is_palindrome("hello"))

"""15. Write a function to calculate the square root of a given number."""

num = float(input("Enter a number: "))
print("Square root:", math.sqrt(num))

"""16. Write a function to find the greatest common divisor (GCD) of two numbers."""

a, b = map(int, input("Enter two numbers: ").split())
print("GCD:", math.gcd(a, b))

"""17. Write a function to check if a given number is a perfect square."""

num = int(input("Enter a number: "))
print(f"{num} is a perfect square" if math.isqrt(num) ** 2 == num else f"{num} is not a perfect square")

"""18. Write a function to generate a list of prime numbers up to a given limit."""

limit = int(input("Enter limit: "))
primes = [num for num in range(2, limit+1) if all(num % i != 0 for i in range(2, int(num ** 0.5) + 1))]
print("Prime numbers:", primes)

"""19. Write a function to check if a given string is an anagram of another string."""

s1 = input("Enter first string: ").lower()
s2 = input("Enter second string: ").lower()
print("Anagram" if sorted(s1) == sorted(s2) else "Not an anagram")

"""20. Write a function to calculate the factorial of a given number using recursion."""

def factorial(n):
    return 1 if n == 0 else n * factorial(n - 1)

num = int(input("Enter a number: "))
print("Factorial:", factorial(num))